trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildVersion: 'net6.0'

steps:
- task: UseDotNet@2
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
     command: test
     projects: '**/*Tests/*.csproj'
     testRunTitle: 'xUNit Test Run'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: src/commandAPI/bin/$(buildConfiguration)/$(buildVersion)
    artifactName: commandAPI